### ISSUE TITLE
Correcte anchor

### ISSUE THREAD

**Issue by DanielvandeVelde** [roobinh/web-app-from-scratch-18-19#1]
https://github.com/roobinh/web-app-from-scratch-18-19/blob/3ada4cb6d50fcc248bba062cdd0552ef29076b55/week1/public/js/app.js#L16

Momenteel linkt dit naar het path op je PC.
Je kan dit ook relatief maken, voor het path naar de 'root' is dit bijvoorbeeld `/`

**Comment by roobinh** [comment]
Thanks, gefixt!
